import test from 'node:test'; import assert from 'node:assert/strict';
import { MemoryStore } from '../src/workers/file-store.js'; import { HedgeCoordinator } from '../src/domain/coordinator.js'; import { DryRunExchangeAdapter } from '../src/exchange-adapter/dry-run.js';
const config = { spotSymbol:'RSTRCUSDT', futuresSymbol:'STRCUSDT', hedgeRatio:'1', qtyStep:'0.01', minQty:'0.01' };
async function setup(){const store=new MemoryStore();await store.init();const alerts=[];const coordinator=new HedgeCoordinator({store,config,notifier:{send:a=>alerts.push(a)}});return {store,coordinator,alerts};}
const event=(overrides={})=>({type:'fill',product:'spot',source:'manual',symbol:'RSTRCUSDT',side:'buy',fillQty:'1.250',tradeId:'t1',orderId:'order123456',timestamp:'2026-09-11T00:00:00Z',...overrides});
test('ACK never creates an intent',async()=>{const {store,coordinator}=await setup();assert.deepEqual(await coordinator.onSpotEvent(event({type:'ack',fillQty:'0'})),{ignored:'ACK_NOT_FILL'});assert.equal(store.snapshot().intents.length,0);});
test('gross buy fill creates futures sell and replay is idempotent',async()=>{const {store,coordinator}=await setup();const first=await coordinator.onSpotEvent(event());await coordinator.onSpotEvent(event());assert.equal(first.intent.side,'sell');assert.equal(first.intent.qty,'1.25');assert.equal(store.snapshot().spotFilledSignedQty,'1.25');assert.equal(store.snapshot().intents.length,1);});
test('gross sell fill creates futures buy',async()=>{const {coordinator}=await setup();const result=await coordinator.onSpotEvent(event({side:'sell'}));assert.equal(result.intent.side,'buy');});
test('STRC quantity is floored to its two-decimal step',async()=>{const {coordinator}=await setup();const result=await coordinator.onSpotEvent(event({fillQty:'1.259'}));assert.equal(result.intent.qty,'1.25');});
test('STRC quantity below its minimum remains residual',async()=>{const {coordinator}=await setup();const result=await coordinator.onSpotEvent(event({fillQty:'0.009'}));assert.deepEqual(result,{residual:'0.009'});});
test('cumulative fills use only positive increment and reject regression',async()=>{const {store,coordinator}=await setup();await coordinator.onSpotEvent(event({tradeId:null,fillQty:'0.4',cumFillQty:'0.4'}));await coordinator.onSpotEvent(event({tradeId:null,fillQty:'0.7',cumFillQty:'0.7'}));assert.equal(store.snapshot().spotFilledSignedQty,'0.7');await assert.rejects(coordinator.onSpotEvent(event({tradeId:null,cumFillQty:'0.6'})),/regressed/);});
test('dry adapter ACK does not increase futures hedged quantity',async()=>{const {store,coordinator}=await setup();const {intent}=await coordinator.onSpotEvent(event());const result=await new DryRunExchangeAdapter(store).submit(intent.id);assert.equal(result.accepted,false);assert.equal(store.snapshot().futuresHedgedSignedQty,'0');});
test('only a confirmed futures fill changes hedged quantity',async()=>{const {store,coordinator}=await setup();await coordinator.onFuturesEvent(event({product:'futures',source:'system',symbol:'STRCUSDT',side:'sell',type:'ack',fillQty:'0'}));assert.equal(store.snapshot().futuresHedgedSignedQty,'0');await coordinator.onFuturesEvent(event({product:'futures',source:'system',symbol:'STRCUSDT',side:'sell',tradeId:'ft1',fillQty:'0.5'}));assert.equal(store.snapshot().futuresHedgedSignedQty,'-0.5');});
